### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by alyssaruth** [mdr/web-sampler#636]
Might do a PR 😁

**Comment by mdr** [comment]
Audio capture for `getDisplayMedia()` is not implemented yet on Firefox unfortunately, see
- https://bugzilla.mozilla.org/show_bug.cgi?id=1541425
- https://caniuse.com/mdn-api_mediadevices_getdisplaymedia_audio_capture_support

If (hopefully "when"!) Firefox implement it, it should start working automatically as we are just detecting whether or not audio tracks are present in the supplied media stream.
